name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DHUB_UNAME: ${{ secrets.DHUB_UNAME }}
  DHUB_PWORD: ${{ secrets.DHUB_PWORD }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag v0idf1sh/treeanalyzer
    - name: Log into Docker Hub
      run: docker login -u $DHUB_UNAME -p $DHUB_PWORD
    - name: Push image to Docker Hub
      run: docker push v0idf1sh/treeanalyzer
